# 베이스 이미지 설정
FROM mariadb

COPY . ./test_db

# WORKDIR /test_db

# RUN mariadb < employees.sql

# 저장소 볼륨 설정
VOLUME ["/exam"]

# 코드 실행
WORKDIR /exam

# RUN rm -rf /test_db

ENTRYPOINT ["mariadb"]
CMD ["test.sql"]



# 이미지 생성
# docker build -t container_sql:latest -f Dockerfile_sql .

# 컨테이너 실행
# docker run --rm --network net-onCoTe -v vol-onCoTe-storage:/exam --env MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 container_sql:latest 

# docker run --rm  -v vol-onCoTe-storage:/exam --env MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 container_sql:latest 